# Generated by Django 3.2.3 on 2021-05-23 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_rename_publishinghouse_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название книги')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('valuta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.valuta')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='books',
            field=models.ManyToManyField(to='directory.Book'),
        ),
    ]
